// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuncnBs-2exfVkJFG4Cbl_1Oal9hgE0vc',
    appId: '1:921509158633:web:1603303e782b06bae3da78',
    messagingSenderId: '921509158633',
    projectId: 'magpusao-advmobprog-2627',
    authDomain: 'magpusao-advmobprog-2627.firebaseapp.com',
    storageBucket: 'magpusao-advmobprog-2627.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj90RPJq7GI14vXrlV4sXdW8TW6FizFHE',
    appId: '1:921509158633:android:e5f863cb6418c420e3da78',
    messagingSenderId: '921509158633',
    projectId: 'magpusao-advmobprog-2627',
    storageBucket: 'magpusao-advmobprog-2627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZWZDBK1LqgH0Ilk05jvpRkSQUvwvrd3g',
    appId: '1:921509158633:ios:3b11b87b38c87ddce3da78',
    messagingSenderId: '921509158633',
    projectId: 'magpusao-advmobprog-2627',
    storageBucket: 'magpusao-advmobprog-2627.firebasestorage.app',
    iosBundleId: 'com.example.magpusaoAdvmobprog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZWZDBK1LqgH0Ilk05jvpRkSQUvwvrd3g',
    appId: '1:921509158633:ios:3b11b87b38c87ddce3da78',
    messagingSenderId: '921509158633',
    projectId: 'magpusao-advmobprog-2627',
    storageBucket: 'magpusao-advmobprog-2627.firebasestorage.app',
    iosBundleId: 'com.example.magpusaoAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuncnBs-2exfVkJFG4Cbl_1Oal9hgE0vc',
    appId: '1:921509158633:web:45e6101952e12a90e3da78',
    messagingSenderId: '921509158633',
    projectId: 'magpusao-advmobprog-2627',
    authDomain: 'magpusao-advmobprog-2627.firebaseapp.com',
    storageBucket: 'magpusao-advmobprog-2627.firebasestorage.app',
  );
}
